### ISSUE TITLE
"copying" pipe not possible

### ISSUE THREAD

**Issue by fabiangehring** [tidyverse/magrittr#173]
```
library(magrittr)
`%>>%` <- `%>%`
"test" %>>% print()
```

surprised me with a "Error in pipes[[i]] : subscript out of bounds" error
If this is not possible for some reason, is there a workaround?

**Comment by smbache** [comment]
No, not as it works atm.

**Comment by hadley** [comment]
This is not a high-priority feature right now.

**Comment by moodymudskipper** [comment]
@hadley @smbache I've been working on a cleaner version of a pipe package and I ended up with a system where copying pipes is natural.

The idea is that instead of having the pipe's actual code stored in the function `wrap_function` it is stored as an attribute to the pipe itself. The pipe gets a class and that's what `is_pipe` tests for instead of testing the symbols. The pipes also get a print method that prints their attribute instead of the full pipe code, which make sense to me as they really are "a different category of functions".

It makes it easy to create new pipes without touching the package code.

These changes are minimal and they shouldn't break much code, the tests were passed smoothly.

In case it might help : 

https://github.com/moodymudskipper/pipes/blob/master/README.md
