### ISSUE TITLE
Pipe does not do what is supposed to do when the function is given with library name and no parens

### ISSUE THREAD

**Issue by balwierz** [tidyverse/magrittr#193]
Not sure if this is fixable or even if it is an unexpected behaviour. 

```r
require(IRanges)
IRanges(start=c(1,5), end=c(6,9)) %>% IRanges::reduce
Error in .::IRanges : unused argument (reduce)

#these two however work:
IRanges(start=c(1,5), end=c(6,9)) %>% IRanges::reduce()
IRanges(start=c(1,5), end=c(6,9)) %>% (IRanges::reduce)
```

**Comment by balwierz** [comment]
@batpigandme : Thanks

An idea if this is not fixable due to the syntax:
When you pipe an object to an unnamed function it throws an error and the user immediately knows what is going on. Maybe the same can be done when a pipe is to a library name?

```r
> 7 %>% function(x) {5 + x}
Error: Anonymous functions myst be parenthesized
```
// Yes it says "myst" not "must" :-)

**Comment by klmr** [comment]
The issue is that `x %>% pkg::fun` is equivalent to ``x %>% `::`(pkg, fun)``. That is, the right-hand side is just a normal function call, and magrittr handles this by injecting the left-hand side as the first argument:

```r
`::`(x, pkg, fun)
```

… which fails because `` `::` `` is as binary operator. The way magrittr handles this is “by design”. The same issue exists for example with `x %>% env$fun`. A straightforward workaround is to simply *always* use parentheses after function calls after the right-hand side in a pipeline. That way you’re using consistent syntax and there’s never any ambiguity (including in other cases, such as [function factories](https://adv-r.hadley.nz/function-factories.html)).

**Comment by balwierz** [comment]
That was my guess what happened.
