### ISSUE TITLE
Strange result using dot

### ISSUE THREAD

**Issue by balwierz** [tidyverse/magrittr#197]
This is correct:
```r
c("a", "b", "c") %>% .[1]
[1] "a"
```

This is unexpected:
```r
c("a", "b", "c") %>% c(.[1])
[1] "a" "b" "c" "a"
```

I don't uderstand what has happened here. If the pipe is evaluated first, `c("a", "b", "c") %>% c` gives a,b,c, but then `c("a", "b", "c") (.[1])` should be syntax error. If . is substituted then it is `c("a", "b", "c") c("a", "b", "c")[1]`, which is still a syntax error.

Yes, `c("a", "b", "c") %>% {c(.[1])}` works fine.
IMHO, `c("a", "b", "c") %>% c(.[1])` should be either the expected behaviour or a syntax error with a warning to use parentheses. Otherwise it can cause a lot of trouble.

**Comment by egnha** [comment]
The behavior you observe is as expected.

The rule is that an expression like
```R
x %>% f(<STUFF>)
```
is equivalent to
```R
. <- x; f(<STUFF>)
```
when `.` appears as an argument of `f`, otherwise
```R
. <- x; f(., <STUFF>)
```
when `.` does **not** appear as an argument of `f`. (The assignment `. <- x` happens in a temporary child environment. You can think of the above expressions as happening in a call to `local()`.)



Thus `x %>% .[1]` has the same effect as `. <- x; .[1]`, because the RHS `.[1]` is actually the call `` `[`(., 1) ``; in particular, you'd get the same result with `` x %>% `[`(1) ``. `x %>% c(.[1])` has the same effect as `. <- x; c(., .[1])`.

**Comment by balwierz** [comment]
Thanks for the explanation

**Comment by smbache** [comment]
Another way to put it is that
```R
c("a", "b", "c") %>% .[1]
```
translates to
```R
`[`(c("a", "b", "c"), 1)
```
and 
```R
c("a", "b", "c") %>% c(.[1])
```
translates to
```R
c(c("a", "b", "c") , c("a", "b", "c")[1])
```

the above is not actually what happens, so the lhs expression is only evaluated once.
