### ISSUE TITLE
Missing/empty name throws error

### ISSUE THREAD

**Issue by burchill** [tidyverse/magrittr#214]
This may be an edge case not worth worrying about, but an empty name seems to mess up the pipes.

```r
library(magrittr)
# Make an empty name
x <- substitute()
# Works fine
identity(x) 
# Error in identity(.) : argument "_lhs" is missing, with no default
x %>% identity() 
```

I don't really see this being a big issue, but I ended up stumbling upon it, so who knows.

**Comment by lionel-** [comment]
I guess you've rearranged the reprex before posting? I see:

```r
x <- substitute()

identity(x)
#> Error in identity(x) : argument "x" is missing, with no default
```

That's because a symbol that evaluates to the missing argument causes the error. What works is a _call_ that returns the missing argument:

```r
identity(substitute())
#>
```

Unfortunately it would be too much trouble to fix this corner case in magrittr, we would have to hide the evaluation behind an extra call. This would affect backtraces for example.
