### ISSUE TITLE
Error: there is no package called 'magrittr'

### ISSUE THREAD

**Issue by annytr** [tidyverse/magrittr#234]
Hello,

There has not been a package called "magrittr" found. Could you help me pls?

```
devtools::install_github("tidyverse/magrittr")
```

Error: .onLoad in loadNamespace () for 'pkgload' failed, details:
   Call: loadNamespace (j <- i [[1L]], c (lib.loc, .libPaths ()), versionCheck = vI [[j]])
   Error: there is no package called 'magrittr'

**Comment by lionel-** [comment]
Close all your RStudio and R sessions. Open a new one and do

```r
remotes::install_github("tidyverse/magrittr")
```

Note the use of `remotes` instead of `devtools`. But you can also just use `install.packages("magrittr")`, it's been released to CRAN.


Also see these tips for safely installing packages on Windows, it's trickier than for other operating systems: https://github.com/rstats-wtf/what-they-forgot/issues/62#issuecomment-545038970
